config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'

  get 'change_currency' => 'spree/home#change_currency'
  get 'save_change_currency' => 'spree/home#save_change_currency'
  get 'back_to_us' => 'spree/home#back_to_us'
  get 'get_currency_from_country' => 'spree/home#get_currency_from_country'

  resources :line_items, only: [:update, :destroy]
  resources :stores, only: [:edit_address]

  get 'load_state/:code', to: 'spree/home#load_state', as: :load_state

  get '/about_us', to: 'spree/public#about_us', as: :about_us
  get '/privacy_policy', to: 'spree/public#privacy_policy', as: :privacy_policy
  get '/term_condition', to: 'spree/public#term_condition', as: :term_condition
  get '/coupon', to: 'spree/public#coupon', as: :coupon

  get '/404', to: 'spree/public#not_found'
  get '/422', to: 'spree/public#unacceptable'
  get '/500', to: 'spree/public#internal_error'
end

Spree::Core::Engine.routes.draw do
  get '/c/*id', to: 'taxons#show', as: :categories
  get '/m/*id', to: 'taxonomies#show', as: :menu
  get '/p/*id', to: 'products#show', as: :brandcruz_product
  get '/brands', to: 'brand#index', as: :brandcruz_brands
  get '/brands/*taxonomy', to: 'brand#index', as: :brandcruz_taxonomy_brands
  get '/b/*id', to: 'brand#show', as: :brandcruz_brand
  get '/product/search', to: 'products#keyword_search', as: :product_search
  get '/free-domestic-shipping-both-ways', to: 'public#domestic', as: :domestic
  match '/dedicated-customer-support', to: 'public#contact_us', via: [:get, :post], as: :contact_us
  get '/free-shipping-worldwide', to: 'public#international', as: :international
  get '/safe_shopping_guarantee', to: 'public#safe_shopping_guarantee', as: :safe_shopping_guarantee
  get '/secure_shopping', to: 'public#secure_shopping', as: :secure_shopping
  get '/forget_password', to: 'public#forget_password', as: :forget_password
  get '/welcome', to: 'public#welcome', as: :welcome
  get '/search_suggestion', to: 'home#search_suggestion', as: :search_suggestion
  get '/order/:id/shipped_track_now', to: 'orders#shipped_track', as: :shipped_track
  get '/admin/orders/:id/tracks', to: 'admin/orders#track', as: :admin_order_track
  get '/brand-cruz-frequently-asked-question', to: 'public#faq', as: :faq
  get '/checkout-sign-up', to: 'checkout#registration', as: :checkout_signup
  get '/secure-checkout-flow-cgn-shipping-address', to: 'checkout#edit', as: :checkout_address
  get '/secure-payment-flow-cng-capture', to: 'checkout#edit', as: :checkout_payment
  post '/apply_coupon', to: 'orders#apply_coupon', as: :apply_coupon
  get '/remove_coupon/:id', to: 'orders#remove_coupon', as: :remove_coupon
  get '/404', to: 'public#not_found'
  get '/422', to: 'public#unacceptable'
  get '/500', to: 'public#internal_error'
  get '/show_cc/:id', to: 'admin/payments#show_cc', as: :show_cc
  patch '/admin/order/:id/update_state/', to: 'admin/orders#update_state', as: :order_state

  devise_scope :spree_user do
    get '/secure-user-signin-signup', to: 'user_sessions#new', as: :user_session
  end
end

app/models/spree/user.rb
module Spree
  class User < Spree::Base
    include UserAddress
    include UserPaymentSource

    devise :database_authenticatable, :registerable, :recoverable,
           :rememberable, :trackable, :validatable, :encryptable, :encryptor => 'authlogic_sha512'
    devise :confirmable if Spree::Auth::Config[:confirmable]

    acts_as_paranoid
    after_destroy :scramble_email_and_password
    after_create :send_welcome_email

    has_many :orders

    before_validation :set_login

    users_table_name = User.table_name
    roles_table_name = Role.table_name

    scope :admin, -> { includes(:spree_roles).where("#{roles_table_name}.name" => "admin") }

    def self.admin_created?
      User.admin.count > 0
    end

    def admin?
      has_spree_role?('admin')
    end

    def send_welcome_email
      Spree::UserMailer.welcome(self).deliver_now
    end

    protected
    def password_required?
      !persisted? || password.present? || password_confirmation.present?
    end

    private

    def set_login
      # for now force login to be same as email, eventually we will make this configurable, etc.
      self.login ||= self.email if self.email
    end

    def scramble_email_and_password
      self.email = SecureRandom.uuid + "@example.net"
      self.login = self.email
      self.password = SecureRandom.hex(8)
      self.password_confirmation = self.password
      self.save
    end
  end
end

app/views/spree/admin/users/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="col-md-6">
    <%= f.field_container :email, class: ['form-group'] do %>
        <%= f.label :email, Spree.t(:email) %>
        <%= f.email_field :email, :class => 'form-control' %>
        <%= f.error_message_on :email %>
    <% end %>

    <% if spree_current_user.has_spree_role?('admin') %>
        <div data-hook="admin_user_form_roles" class="form-group">
          <strong><%= Spree.t(:roles) %></strong>
          <%= f.collection_check_boxes :spree_role_ids, Spree::Role.all, :id, :name do |role_form| %>
              <div class="checkbox">
                <%= role_form.label for: "user_spree_role_#{role_form.object.name}" do %>
                    <%= role_form.check_box id: "user_spree_role_#{role_form.object.name}" %>
                    <%= role_form.object.name %>
                <% end %>
              </div>
          <% end %>
        </div>
    <% end %>

  </div>

  <div data-hook="admin_user_form_password_fields" class="col-md-6">
    <%= f.field_container :password, class: ['form-group'] do %>
        <%= f.label :password, Spree.t(:password) %>
        <%= f.password_field :password, :class => 'form-control' %>
        <%= f.error_message_on :password %>
    <% end %>

    <%= f.field_container :password_confirmation, class: ['form-group'] do %>
        <%= f.label :password_confirmation, Spree.t(:confirm_password) %>
        <%= f.password_field :password_confirmation, :class => 'form-control' %>
        <%= f.error_message_on :password_confirmation %>
    <% end %>
  </div>
</div>

app/views/spree/admin/users/_sidebar.html.erb
<% content_for :page_title do %>
    <%= link_to Spree.t(:users), spree.admin_users_path %> /
<% end %>

<% content_for :sidebar do %>
    <ul class="nav nav-pills nav-stacked" data-hook="admin_user_tab_options">
      <li<%== ' class="active"' if current == :account %>>
        <%= link_to_with_icon 'user', Spree.t(:"admin.user.account"), spree.edit_admin_user_path(@user) %>
      </li>
      <li<%== ' class="active"' if current == :address %>>
        <%= link_to_with_icon 'user', Spree.t(:"admin.user.addresses"), spree.addresses_admin_user_path(@user) %>
      </li>
      <li<%== ' class="active"' if current == :orders %>>
        <%= link_to_with_icon 'shopping-cart', Spree.t(:"admin.user.orders"), spree.orders_admin_user_path(@user) %>
      </li>
      <li<%== ' class="active"' if current == :items %>>
        <%= link_to_with_icon 'edit', Spree.t(:"admin.user.items"), spree.items_admin_user_path(@user) %>
      </li>
      <% if spree_current_user.has_spree_role?('admin') %>
          <li<%== ' class="active"' if current == :store_credits %>>
            <%= link_to_with_icon 'money', Spree.t(:"admin.user.store_credits"), spree.admin_user_store_credits_path(@user) %>
          </li>
      <% end %>
    </ul>
<% end %>

app/views/spree/admin/users/edit.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :account } %>
<%= render partial: 'spree/admin/users/user_page_actions' %>

<% content_for :page_title do %>
  <%= @user.email %>
<% end %>

<div data-hook="admin_user_edit_general_settings" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= Spree.t(:general_settings) %>
    </h1>
  </div>

  <div class="panel-body">
    <div data-hook="admin_user_edit_form_header">
      <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user } %>
    </div>

    <div data-hook="admin_user_edit_form">
      <%= form_for [:admin, @user], as: :user, url: spree.admin_user_url(@user), method: :put do |f| %>
        <%= render partial: 'form', locals: { f: f } %>

        <div data-hook="admin_user_edit_form_button">
          <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_users_url } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div data-hook="admin_user_api_key" id="admin_user_edit_api_key" class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= Spree.t('access', scope: 'api') %>
    </h1>
  </div>

  <div class="panel-body">
    <% if @user.spree_api_key.present? %>
      <div class="form-group">
        <div id="current-api-key">
          <label><%= Spree.t('key', scope: 'api') %>: </label>
          <strong><%= @user.spree_api_key %></strong>
        </div>
      </div>
      <div class="form-actions">
        <%= form_tag spree.clear_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('clear_key', scope: 'api'), 'delete', 'submit', class: "btn-danger" %>
        <% end %>

        <span class="or"><%= Spree.t(:or)%></span>

        <%= form_tag spree.generate_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('regenerate_key', scope: 'api'), 'save' %>
        <% end %>
      </div>

    <% else %>

      <div class="alert alert-warning"><%= Spree.t('no_key', scope: 'api') %></div>

      <div class="form-actions">
        <%= form_tag spree.generate_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('generate_key', scope: 'api'), 'key' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'spree/admin/users/lifetime_stats' %>

app/views/spree/admin/users/index.html.erb
<% content_for :page_title do %>
    <%= Spree.t(:users) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_user), new_admin_user_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_user_link' %>
<% end %>

<% content_for :table_filter_title do %>
    <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
    <div data-hook="admin_users_index_search">
      <%= search_form_for [:admin, @search], url: spree.admin_users_url do |f| %>
          <div class="form-group">
            <%= f.label Spree.t(:email) %>
            <%= f.text_field :email_cont, class: "form-control js-quick-search-target" %>
          </div>
          <div class="row">
            <!--<div class="col-md-6">-->
            <!--<div class="form-group">-->
            <!--<%#= f.label Spree.t(:first_name) %>-->
            <!--<%#= f.text_field :bill_address_firstname_cont, :class => 'form-control' %>-->
            <!--</div>-->
            <!--</div>-->
            <!--<div class="col-md-6">-->
            <!--<div class="form-group">-->
            <!--<%#= f.label Spree.t(:last_name) %>-->
            <!--<%#= f.text_field :bill_address_lastname_cont, :class => 'form-control' %>-->
            <!--</div>-->
            <!--</div>-->
          </div>
          <!--<div class="form-group">-->
            <!--<%#= f.label Spree.t(:company) %>-->
            <!--<%#= f.text_field :bill_address_company_cont, :class => 'form-control' %>-->
          <!--</div>-->
          <div data-hook="admin_users_index_search_buttons" class="form-actions">
            <%= button Spree.t(:search), 'search' %>
          </div>
      <% end %>
    </div>
<% end %>

<table class="table" id="listing_users" data-hook>
  <thead>
  <tr data-hook="admin_users_index_headers">
    <th>
      <%= sort_link @search, :email, Spree.t(:user), {}, {:title => 'users_email_title'} %>
    </th>
    <th data-hook="admin_users_index_header_actions" class="actions"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr id="<%= spree_dom_id user %>" data-hook="admin_users_index_rows">
        <td class='user_email'><%= link_to user.email, edit_admin_user_url(user) %></td>
        <td data-hook="admin_users_index_row_actions" class="actions actions-2 text-right">
          <%= link_to_edit user, :no_text => true if can? :edit, user %>
          <%= link_to_delete user, :no_text => true if can? :delete, user %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/spree/admin/users/items.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: {current: :items} %>
<%= render partial: 'spree/admin/users/user_page_actions' %>

<% content_for :page_title do %>
    <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
    <%= Spree.t(:"admin.user.items_purchased") %>
<% end %>

<fieldset data-hook="admin_user_items_purchased">
  <%= paginate @orders %>

  <% if @orders.any? %>
      <%# TODO add search interface %>
      <table class="table table-condensed table-bordered stock-contents" id="listing_items" data-hook="stock-contents">
        <thead>
        <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_completed_at_title'} %></th>
        <th colspan=2><%= Spree.t(:description) %></th>
        <th><%= I18n.t(:price, scope: 'activerecord.attributes.spree/line_item') %></th>
        <th><%= I18n.t(:quantity, scope: 'activerecord.attributes.spree/line_item') %></th>
        <th><%= Spree.t(:total) %></th>
        <th><%= sort_link @search, :state, I18n.t(:state, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_state_title'} %></th>
        <th><%= sort_link @search, :number, Spree.t(:order_num, scope: 'admin.user'), {}, {title: 'orders_number_title'} %></th>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
            <% order.line_items.each do |item| %>
                <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
                  <td class="order-completed-at"><%= order_time(order.completed_at) if order.completed_at %></td>
                  <td class="item-image">
                    <%= get_small_variant_image(item.variant) %>
                  </td>
                  <td class="item-name">
                    <%= item.product.name %>
                    <br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
                    <% if item.variant.sku.present? %>
                        <strong><%= Spree.t(:sku) %>:</strong> <%= item.variant.sku %>
                    <% end %>
                  </td>
                  <td class="item-price"><%= item.single_money.to_html %></td>
                  <td class="item-quantity"><%= item.quantity %></td>
                  <td class="item-total"><%= item.money.to_html %></td>
                  <td class="order-state">
                    <div class="state <%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></div>
                    <% if order.payment_state %>
                        <div class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></div>
                    <% end %>
                    <% if Spree::Order.checkout_step_names.include?(:delivery) && order.shipment_state %>
                        <div class="state <%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></div>
                    <% end %>
                  </td>
                  <td class="order-number"><%= link_to order.number, edit_admin_order_url(order) %></td>
                </tr>
            <% end %>
        <% end %>
        </table>
  <% else %>
      <div class="alert alert-info no-objects-found">
        <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
        <%= link_to Spree.t(:add_one), spree.new_admin_order_path %>!
      </div>
  <% end %>
  <%= paginate @orders %>
</fieldset>

<%= render 'spree/admin/users/lifetime_stats' %>