config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'

  get 'change_currency' => 'spree/home#change_currency'
  get 'save_change_currency' => 'spree/home#save_change_currency'
  get 'back_to_us' => 'spree/home#back_to_us'
  get 'get_currency_from_country' => 'spree/home#get_currency_from_country'

  resources :line_items, only: [:update, :destroy]
  resources :stores, only: [:edit_address]

  get 'load_state/:code', to: 'spree/home#load_state', as: :load_state

  get '/about_us', to: 'spree/public#about_us', as: :about_us
  get '/privacy_policy', to: 'spree/public#privacy_policy', as: :privacy_policy
  get '/term_condition', to: 'spree/public#term_condition', as: :term_condition
  get '/coupon', to: 'spree/public#coupon', as: :coupon

  get '/404', to: 'spree/public#not_found'
  get '/422', to: 'spree/public#unacceptable'
  get '/500', to: 'spree/public#internal_error'
end

Spree::Core::Engine.routes.draw do
  get '/c/*id', to: 'taxons#show', as: :categories
  get '/m/*id', to: 'taxonomies#show', as: :menu
  get '/p/*id', to: 'products#show', as: :brandcruz_product
  get '/brands', to: 'brand#index', as: :brandcruz_brands
  get '/brands/*taxonomy', to: 'brand#index', as: :brandcruz_taxonomy_brands
  get '/b/*id', to: 'brand#show', as: :brandcruz_brand
  get '/product/search', to: 'products#keyword_search', as: :product_search
  get '/free-domestic-shipping-both-ways', to: 'public#domestic', as: :domestic
  match '/dedicated-customer-support', to: 'public#contact_us', via: [:get, :post], as: :contact_us
  get '/free-shipping-worldwide', to: 'public#international', as: :international
  get '/safe_shopping_guarantee', to: 'public#safe_shopping_guarantee', as: :safe_shopping_guarantee
  get '/secure_shopping', to: 'public#secure_shopping', as: :secure_shopping
  get '/forget_password', to: 'public#forget_password', as: :forget_password
  get '/welcome', to: 'public#welcome', as: :welcome
  get '/search_suggestion', to: 'home#search_suggestion', as: :search_suggestion
  get '/order/:id/shipped_track_now', to: 'orders#shipped_track', as: :shipped_track
  get '/admin/orders/:id/tracks', to: 'admin/orders#track', as: :admin_order_track
  get '/brand-cruz-frequently-asked-question', to: 'public#faq', as: :faq
  get '/checkout-sign-up', to: 'checkout#registration', as: :checkout_signup
  get '/secure-checkout-flow-cgn-shipping-address', to: 'checkout#edit', as: :checkout_address
  get '/secure-payment-flow-cng-capture', to: 'checkout#edit', as: :checkout_payment
  post '/apply_coupon', to: 'orders#apply_coupon', as: :apply_coupon
  get '/remove_coupon/:id', to: 'orders#remove_coupon', as: :remove_coupon
  get '/404', to: 'public#not_found'
  get '/422', to: 'public#unacceptable'
  get '/500', to: 'public#internal_error'
  get '/show_cc/:id', to: 'admin/payments#show_cc', as: :show_cc
  patch '/admin/order/:id/update_state/', to: 'admin/orders#update_state', as: :order_state

  devise_scope :spree_user do
    get '/secure-user-signin-signup', to: 'user_sessions#new', as: :user_session
  end
end

app/models/spree/address.rb
module Spree
  class Address < Spree::Base
    require 'twitter_cldr'

    belongs_to :country, class_name: "Spree::Country"
    belongs_to :state, class_name: "Spree::State"

    has_many :shipments, inverse_of: :address

    with_options presence: true do
      # validates :firstname, :lastname, :address1, :city, :country
      validates :address1, :city, :country
      validates :zipcode, if: :require_zipcode?
      validates :phone, if: :require_phone?
    end

    validate :state_validate, :postal_code_validate

    alias_attribute :first_name, :firstname
    alias_attribute :last_name, :lastname

    # self.whitelisted_ransackable_attributes = %w[firstname lastname company]

    def self.build_default
      new
    end

    def self.default(user = nil, kind = "bill")
      if user && user_address = user.public_send(:"#{kind}_address")
        user_address.clone
      else
        build_default
      end
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def name
      "#{first_name} #{last_name}".strip
    end

    def name=(full_name)
      f_name = full_name.split(' ', 2)
      self.first_name = f_name.first
      self.last_name = f_name.last if f_name.length > 1
    end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
          name: full_name,
          address1: address1,
          address2: address2,
          city: city,
          state: state_text,
          zip: zipcode,
          country: country.try(:iso),
          phone: phone
      }
    end

    def require_phone?
      true
    end

    def require_zipcode?
      true
    end

    private
    def state_validate
      # Skip state validation without country (also required)
      # or when disabled by preference
      return if country.blank? || !Spree::Config[:address_requires_state]
      return unless country.states_required

      # ensure associated state belongs to country
      if state.present?
        if state.country == country
          self.state_name = nil #not required as we have a valid state and country combo
        else
          if state_name.present?
            self.state = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
      if state_name.present?
        if country.states.present?
          states = country.states.find_all_by_name_or_abbr(state_name)

          if states.size == 1
            self.state = states.first
            self.state_name = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure at least one state field is populated
      errors.add :state, :blank if state.blank? && state_name.blank?
    end

    def postal_code_validate
      return if country.blank? || country.iso.blank? || !require_zipcode?
      return if !TwitterCldr::Shared::PostalCodes.territories.include?(country.iso.downcase.to_sym)

      postal_code = TwitterCldr::Shared::PostalCodes.for_territory(country.iso)
      errors.add(:zipcode, :invalid) if !postal_code.valid?(zipcode.to_s.strip)
    end
  end
end

app/models/spree/asset.rb
module Spree
  class Asset < Spree::Base
    belongs_to :viewable, polymorphic: true, touch: true
    acts_as_list scope: [:viewable_id, :viewable_type]
  end
end

app/models/spree/brand.rb
module Spree
  class Brand < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    has_many :products, :class_name => 'Spree::Product'

    def slug_candidates
      [
          :name,
          [:name, :id],
      ]
    end

    def self.replace_macys
      mac_brands = self.where("lower(name) like '%macy%'")
      mac_brands.each do |br|
        if br.name.include? "Macy's"
          br.name = br.name.gsub("Macy's", "Brandcruz")
          br.slug = br.slug.present? ? br.slug.gsub("macy-s", "brandcruz") : 'brandcruz'
        else
          br.name = "Brandcruz"
          br.slug = "brandcruz"
        end
        br.save
        p "Info: ID: #{br.id} and url: #{br.slug}"
      end
    end

  end
end

app/models/spree/classification.rb
module Spree
  class Classification < Spree::Base
    self.table_name = 'spree_products_taxons'
    acts_as_list scope: :taxon

    with_options inverse_of: :classifications, touch: true do
      belongs_to :product, class_name: "Spree::Product"
      belongs_to :taxon, class_name: "Spree::Taxon"
    end

    validates :taxon, :product, presence: true
    # For #3494
    validates :taxon_id, uniqueness: { scope: :product_id, message: :already_linked, allow_blank: true }
  end
end

app/models/spree/credit_card.rb
module Spree
  class CreditCard < Spree::Base
    belongs_to :payment_method
    belongs_to :user, class_name: Spree.user_class, foreign_key: 'user_id'
    has_many :payments, as: :source

    before_save :set_last_digits

    after_save :ensure_one_default

    # As of rails 4.2 string columns always return strings, we can override it on model level.
    attribute :month, Type::Integer.new
    attribute :year, Type::Integer.new

    attr_reader :number
    attr_accessor :encrypted_data,
                  :imported,
                  :verification_value

    with_options if: :require_card_numbers?, on: :create do
      validates :month, :year, numericality: {only_integer: true}
      # validates :number, :verification_value, presence: true, unless: :imported
      validates :name, presence: true
    end

    scope :with_payment_profile, -> { where('gateway_customer_profile_id IS NOT NULL') }
    scope :default, -> { where(default: true) }

    # needed for some of the ActiveMerchant gateways (eg. SagePay)
    alias_attribute :brand, :cc_type

    # ActiveMerchant::Billing::CreditCard added this accessor used by some gateways.
    # More info: https://github.com/spree/spree/issues/6209
    #
    # Returns or sets the track data for the card
    #
    # @return [String]
    attr_accessor :track_data

    CARD_TYPES = {
        visa: /^4\d{12}(\d{3})?(\d{3})?$/,
        master: /^(5[1-5]\d{4}|677189|222[1-9]\d{2}|22[3-9]\d{3}|2[3-6]\d{4}|27[01]\d{3}|2720\d{2})\d{10}$/,
        discover: /^(6011|65\d{2}|64[4-9]\d)\d{12}|(62\d{14})$/,
        american_express: /^3[47]\d{13}$/,
        diners_club: /^3(0[0-5]|[68]\d)\d{11}$/,
        jcb: /^35(28|29|[3-8]\d)\d{12}$/,
        switch: /^6759\d{12}(\d{2,3})?$/,
        solo: /^6767\d{12}(\d{2,3})?$/,
        dankort: /^5019\d{12}$/,
        maestro: /^(5[06-8]|6\d)\d{10,17}$/,
        forbrugsforeningen: /^600722\d{10}$/,
        laser: /^(6304|6706|6709|6771(?!89))\d{8}(\d{4}|\d{6,7})?$/
    }

    def expiry=(expiry)
      return unless expiry.present?

      self[:month], self[:year] =
          if expiry.match(/\d{2}\s?\/\s?\d{2,4}/) # will match mm/yy and mm / yyyy
            expiry.delete(' ').split('/')
          elsif match = expiry.match(/(\d{2})(\d{2,4})/) # will match mmyy and mmyyyy
            [match[1], match[2]]
          end
      if self[:year]
        self[:year] = "20#{ self[:year] }" if self[:year] / 100 == 0
        self[:year] = self[:year].to_i
      end
      self[:month] = self[:month].to_i if self[:month]
    end

    def number=(num)
      @number = num.gsub(/[^0-9]/, '') rescue nil
    end

    # cc_type is set by jquery.payment, which helpfully provides different
    # types from Active Merchant. Converting them is necessary.
    def cc_type=(type)
      self[:cc_type] = case type
                         when 'mastercard', 'maestro' then
                           'master'
                         when 'amex' then
                           'american_express'
                         when 'dinersclub' then
                           'diners_club'
                         when '' then
                           try_type_from_number
                         else
                           type
                       end
    end

    def set_last_digits
      number.to_s.gsub!(/\s/, '')
      verification_value.to_s.gsub!(/\s/, '')
      self.last_digits ||= number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
    end

    def try_type_from_number
      numbers = number.delete(' ') if number
      CARD_TYPES.find { |type, pattern| return type.to_s if numbers =~ pattern }.to_s
    end

    def verification_value?
      verification_value.present?
    end

    # Show the card number, with all but last 4 numbers replace with "X". (XXXX-XXXX-XXXX-4338)
    def display_number
      "XXXX-XXXX-XXXX-#{last_digits}"
    end

    def actions
      %w{capture void credit}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      payment.pending? || payment.checkout?
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      !payment.failed? && !payment.void?
    end

    # Indicates whether its possible to credit the payment.  Note that most gateways require that the
    # payment be settled first which generally happens within 12-24 hours of the transaction.
    def can_credit?(payment)
      payment.completed? && payment.credit_allowed > 0
    end

    def has_payment_profile?
      gateway_customer_profile_id.present? || gateway_payment_profile_id.present?
    end

    # ActiveMerchant needs first_name/last_name because we pass it a Spree::CreditCard and it calls those methods on it.
    # Looking at the ActiveMerchant source code we should probably be calling #to_active_merchant before passing
    # the object to ActiveMerchant but this should do for now.
    def first_name
      name.to_s.split(/[[:space:]]/, 2)[0]
    end

    def last_name
      name.to_s.split(/[[:space:]]/, 2)[1]
    end

    def to_active_merchant
      ActiveMerchant::Billing::CreditCard.new(
          number: number,
          month: month,
          year: year,
          verification_value: verification_value,
          first_name: first_name,
          last_name: last_name,
      )
    end

    private

    def require_card_numbers?
      !self.encrypted_data.present? && !self.has_payment_profile?
    end

    def ensure_one_default
      if self.user_id && self.default
        CreditCard.where(default: true, user_id: self.user_id).where.not(id: self.id)
            .update_all(default: false)
      end
    end
  end
end

app/models/spree/member_product.rb
module Spree
  class MemberProduct < ActiveRecord::Base
    belongs_to :product, class_name: 'Spree::Product'
    belongs_to :member, class_name: 'Spree::Product', foreign_key: :member_id
  end
end

app/models/spree/order_track.rb
module Spree
  class OrderTrack < ActiveRecord::Base
    belongs_to :order, class_name: 'Spree::Order'
  end
end

app/models/spree/recommendation.rb
module Spree
  class Recommendation < ActiveRecord::Base
    belongs_to :product, class_name: 'Spree::Product'
    belongs_to :recommend_product, class_name: 'Spree::Product', foreign_key: :recommended_product_id

    def own_product
      Spree::Product.find_by_id(self.id)
    end
  end
end

app/models/spree/size.rb
module Spree
  class Size < ActiveRecord::Base
    belongs_to :product, :class_name => 'Spree::Product'
  end
end

app/models/spree/taxonomy.rb
module Spree
  class Taxonomy < Spree::Base
    acts_as_list
    extend FriendlyId
    friendly_id :name, use: :slugged

    validates :name, presence: true

    has_many :taxons, inverse_of: :taxonomy
    has_one :root, -> { where parent_id: nil }, class_name: "Spree::Taxon", dependent: :destroy

    has_many :top_categories, -> { where parent_id: nil }, class_name: "Spree::Taxon"

    after_create :set_root
    after_save :set_root_taxon_name

    default_scope { order("#{self.table_name}.position, #{self.table_name}.created_at") }

    private
    def set_root
      self.root ||= Taxon.create!(taxonomy_id: id, name: name)
    end

    def set_root_taxon_name
      root.update_attributes(name: name)
    end
  end
end

app/models/spree/user.rb
module Spree
  class User < Spree::Base
    include UserAddress
    include UserPaymentSource

    devise :database_authenticatable, :registerable, :recoverable,
           :rememberable, :trackable, :validatable, :encryptable, :encryptor => 'authlogic_sha512'
    devise :confirmable if Spree::Auth::Config[:confirmable]

    acts_as_paranoid
    after_destroy :scramble_email_and_password
    after_create :send_welcome_email

    has_many :orders

    before_validation :set_login

    users_table_name = User.table_name
    roles_table_name = Role.table_name

    scope :admin, -> { includes(:spree_roles).where("#{roles_table_name}.name" => "admin") }

    def self.admin_created?
      User.admin.count > 0
    end

    def admin?
      has_spree_role?('admin')
    end

    def send_welcome_email
      Spree::UserMailer.welcome(self).deliver_now
    end

    protected
    def password_required?
      !persisted? || password.present? || password_confirmation.present?
    end

    private

    def set_login
      # for now force login to be same as email, eventually we will make this configurable, etc.
      self.login ||= self.email if self.email
    end

    def scramble_email_and_password
      self.email = SecureRandom.uuid + "@example.net"
      self.login = self.email
      self.password = SecureRandom.hex(8)
      self.password_confirmation = self.password
      self.save
    end
  end
end

app/controllers/spree/admin/admin_base_decorator.rb
Spree::Admin::BaseController.class_eval do
  def authorize_admin
    if respond_to?(:model_class, true) && model_class
      record = model_class
    else
      record = Object
    end
    authorize! :admin, record
    authorize! action, record
  end
end

app/views/spree/checkout/_address.html.erb
<div class="container">
  <div class="checkout-header checkout-menu-block address">
    <div class="flex-itemsx-md-middle clearfix" style="margin-left: -15px; margin-right: -15px;">
      <div class="col-lg-6 text-lg-right pull-right">
        <ul class="mb-20">
          <li> <%= link_to 'Contact Us', '/dedicated-customer-support', target: '_blank' %> </li>
          <li><a href="https://lc.chat/now/8866794" target="_blank">Chat</a></li>
          <li>
            <a href="<%= cookies[:country_code] == 'US' ? domestic_path : spree.international_path %>" target="_blank">
              Shipping &amp; Returns
            </a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6 pull-left">
        <div class="progress-bar-img1">
          <%= image_tag 'checkout-01.jpg' %>
        </div>
      </div>
    </div>
  </div>

  <div class="clear"></div>
  <div class="row">
    <div class="col-md-5 clearfix">
      <ul class="checkout-menu">
        <li class="checkout-current"> Your shipping address</li>
      </ul>
      <div class="checkout-form">
        <div class="row">
          <div class="col-md-12 shipping-address-form">
            <%= form.fields_for :ship_address do |ship_form| %>
                <%= render 'spree/checkout/address_fields', form_builder: ship_form, address_type: 'Shipping' %>
                <hr style="margin-top: 40px">
                <%= form.check_box :use_shipping, value: true, checked: true, class: 'hidden' %>
                <%= hidden_field_tag :failed_id, params[:failed_id] %>
                <div class="shipping-method">
                  <h3> SHIPPING METHOD </h3>
                  <ul class="common-ul-style custom-radio-btn clearfix input-wrap">
                    <% method_keys = static_shipment_method.keys %>
                    <% saved_shipment_method = form.object.shipments.present? && form.object.shipments.tracking.present? ? form.object.shipments.tracking : '' %>
                    <li>
                      <%= radio_button_tag "order[shipments_attributes]", 'standard', method_keys.include?(saved_shipment_method.downcase), id: 'shipments_method_Standard', checked: true %>
                      <span class="form-error"></span>
                      <label for="shipments_method_Standard">
                        <div class="label-wrap">
                          Standard <strong> Free </strong>

                          <p>
                            Transit time: 3-6 business days
                          </p>
                        </div>
                      </label>

                      <div class="check"></div>
                    </li>
                    <li data-toggle="tooltip" title="This shipping method currently unavailable">
                      <%#= radio_button_tag "order[shipments_attributes]", 'premium', method_keys.include?(saved_shipment_method.downcase), id: 'shipments_method_Premium'%>
                      <span class="form-error"></span>
                      <label for="shipments_method_Premium">
                        <div class="label-wrap">
                          Premium <strong style="color: #c6c6c6;"> $9.00 </strong>

                          <p>
                            Transit time: 2-3 business days
                          </p>
                        </div>
                      </label>

                      <div class="check"></div>
                    </li>
                    <li data-toggle="tooltip" title="This shipping method currently unavailable">
                      <%#= radio_button_tag "order[shipments_attributes]", 'express', method_keys.include?(saved_shipment_method.downcase), id: 'shipments_method_Express'%>
                      <span class="form-error"></span>
                      <label for="shipments_method_Express">
                        <div class="label-wrap">
                          Express <strong style="color: #c6c6c6;"> $19.00 </strong>

                          <p>
                            Transit time: 1-2 business days
                          </p>
                        </div>
                      </label>

                      <div class="check"></div>
                    </li>
                  </ul>
                  <!--<div>-->
                  <!--<%#= image_tag 'disable-radio-btn.jpg' %>-->
                  <!--</div>-->
                </div>

                <hr style="margin-top: 40px">

                <div class="gift-option">
                  <h3> GIFT OPTIONS </h3>
                  <hr>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox">
                      This order contains a gift
                    </label>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="text-xs-right pull-md-right">
        <%= submit_tag 'Save and Continue', :class => 'button button-primary button-large' %>
      </div>
    </div>
    <div class="col-md-7 clearfix">
      <%= render 'spree/orders/summary' %>
    </div>
  </div>
</div>

<%= render 'spree/shared/form_validation_script' %>

app/views/spree/checkout/_payment.html.erb
<script type="text/javascript" asyc src='https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/3.0.0/jquery.payment.min.js'></script>
<div class="container">
  <div class="checkout-header checkout-menu-block payment">
    <div class="flex-itemsx-md-middle clearfix" style="margin-left: -15px; margin-right: -15px;">
      <div class="col-lg-6 text-lg-right pull-right">
        <ul class="mb-20">
          <li> <%= link_to 'Contact Us', '/dedicated-customer-support', target: '_blank' %> </li>
          <li><a href="https://lc.chat/now/8866794/" target="_blank">Chat</a></li>
          <li>
            <a href="<%= cookies[:country_code] == 'US' ? domestic_path : spree.international_path %>" target="_blank">
              Shipping &amp; Returns
            </a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6 pull-left">
        <div class="progress-bar-img1">
          <%= image_tag 'checkout-02.jpg' %>
        </div>
      </div>
    </div>
  </div>

  <div class="clear"></div>
  <ul class="checkout-menu">
    <li class="checkout-current"> Review & Payments</li>
  </ul>
  <div class="row">

    <div class="col-md-5 clearfix">
      <div class="border-bottom" style="margin-bottom: 20px; padding-bottom: 50px">
        <div class="row">
          <div class="col-sm-6 shipping-address">
            <h4> Shipping address </h4>
            <%= form.fields_for :ship_address do |ship_form| %>
                <p>
                  <%= ship_form.object.active_merchant_hash[:name] %> <br/>
                  <%= ship_form.object.active_merchant_hash[:address1] %> <br/>
                  <%= ship_form.object.active_merchant_hash[:city] + ', ' + ship_form.object.active_merchant_hash[:zip] %>
                  <br/>
                  <%= ship_form.object.active_merchant_hash[:phone] %>
                </p>
            <% end %>
            <% if params[:failed_id].present? %>
                <%= link_to 'EDIT', spree.checkout_address_path(state: 'address', failed_id: params[:failed_id]), class: 'btn-edit' %>
            <% else %>
                <%= link_to 'EDIT', spree.checkout_address_path(state: 'address'), class: 'btn-edit' %>
            <% end %>
          </div>
          <div class="col-sm-6 shipping-method">
            <h4> Shipping method </h4>

            <p>
              Standard
              3-6 business days
            </p>
          </div>
        </div>
      </div>
      <form action="" role="form" method="post">
        <div class="chose-payment-method border-bottom" style="margin-bottom: 20px; padding-bottom: 50px">
          <h3> CHOOSE PAYMENT METHOD </h3>

          <div class="payment-method-form">
            <div class="payment-method-form-container">
              <div class="form-group input-wrap">
                <label for="card-no">
                  Card number
                </label>
                <%= image_tag('ssl_cert.png', class: 'pull-right', width: '36px') %>
                <%= hidden_field_tag "[order][payments_attributes][amount]", @order.total, class: 'required form-control' %>
                <%= hidden_field_tag "[order][payments_attributes][name]", '', class: 'form-control' %>
                <%= text_field_tag "[order][payments_attributes][number]", '', class: 'required form-control mt10' %>
                <span class="form-error"></span>
              </div>

              <div class="form-group input-wrap">
                <label for="card-no">
                  Name on Card
                </label>
                <%= text_field_tag "[order][payments_attributes][name]", '', class: 'form-control required' %>
                <span class="form-error"></span>
              </div>

              <div class="form-group input-wrap">
                <label for="expiration-date"> Expiration date </label>
                <%= text_field_tag '[order][payments_attributes][expire]', '', id: "expiration-date", class: "form-control required", placeholder: 'MM/YY' %>
                <span class="form-error"></span>
              </div>
              <%= hidden_field_tag :failed_id, params[:failed_id] %>
              <div class="form-group input-wrap">
                <label for="security-code"> CVV </label>
                <%= text_field_tag "[order][payments_attributes][cvv_response_code]", '', class: 'required form-control' %>
                <span class="form-error"></span>
              </div>
            </div>
          </div>
        </div>
        <div class="billing-address">
          <div class="billing-address">
            <h3> BILLING ADDRESS </h3>

            <div class="radio-btn-shipping-address">
              <div class="checkbox">
                <label>
                  <%= form.check_box :use_shipping, value: true, checked: true, id: "same-billing-address" %>
                  <span> Use my shipping address </span>
                  <%= form.fields_for :ship_address do |ship_form| %>
                      <p>
                        <%= ship_form.object.active_merchant_hash[:name] %>
                        <%= ship_form.object.active_merchant_hash[:address1] %>
                        <%= ship_form.object.active_merchant_hash[:city] + ', ' + ship_form.object.active_merchant_hash[:zip] %>
                      </p>
                  <% end %>
                </label>
              </div>
            </div>
          </div>
        </div>

        <div class="billing-address-form">
          <%= form.fields_for :bill_address do |ship_form| %>
              <div id="custom-billing-address" class="billing-address-form-container collapse">
                <%= render 'spree/checkout/address_fields', form_builder: ship_form, address_type: 'Billing' %>
              </div>
          <% end %>
        </div>

        <div class="continue-btn clearfix">
          <input type="submit" class="pull-md-right" value="CONTINUE">
        </div>
      </form>
    </div>

    <div class="col-md-7 clearfix">
      <%= render 'spree/orders/summary' %>
    </div>
  </div>
</div>

<%= render 'spree/shared/form_validation_script' %>

<script type="text/javascript">
    $(function () {
        $('#same-billing-address').click(function () {
            if ($(this).is(":checked")) {
                $('#custom-billing-address').slideUp();
            }
            else {
                $('#custom-billing-address').slideDown();
            }
        });
        card = $('#_order_payments_attributes_number');
        cvv = $('#_order_payments_attributes_cvv_response_code');
        expire = $('#expiration-date');

        card.payment('formatCardNumber');
        cvv.payment('formatCardCVC');
        expire.payment('formatCardExpiry');

        $('input[type="submit"]').click(function (e) {
            valid_card = $.payment.validateCardNumber(card.val());
            valid_cvv = $.payment.validateCardCVC(cvv.val());
            valid_expire = $.payment.cardExpiryVal(expire.val());

            if (!valid_card) {
                card.removeClass('valid');
                card.parent().addClass('errored');
                card.next().html("Your card number is invalid");
            }

            if (!valid_cvv) {
                cvv.removeClass('valid');
                cvv.parent().addClass('errored');
                cvv.next().html("Your card cvc is invalid");
            }

            if (!valid_expire) {
                expire.removeClass('valid');
                expire.parent().addClass('errored');
                expire.next().html("Your card expire is invalid");
            }

            if (!(valid_card && valid_cvv && valid_expire)) {
                console.log("Invalid payment credential");
                e.preventDefault();
            }
            else {
                console.log("Valid payment");
            }
        });

//        card.keyup(function () {
//            card_type = $.payment.cardType($(this).val());
//            card_name = $("#_order_payments_attributes_name");
//            if (card_type != '') {
//                card_name.val(card_type);
//            }
//            else {
//                card_name.val(card_type);
//            }
//        });
    });
</script>

app/views/spree/checkout/edit.html.erb
<div id="main-container">
  <%= form_for @order, url: update_checkout_path(@order.state), html: {id: "checkout_form_#{@order.state}"} do |form| %>
      <%= form.hidden_field :state_lock_version %>
      <%= render @order.state, form: form %>
  <% end %>
</div>