config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'

  get 'change_currency' => 'spree/home#change_currency'
  get 'save_change_currency' => 'spree/home#save_change_currency'
  get 'back_to_us' => 'spree/home#back_to_us'
  get 'get_currency_from_country' => 'spree/home#get_currency_from_country'

  resources :line_items, only: [:update, :destroy]
  resources :stores, only: [:edit_address]

  get 'load_state/:code', to: 'spree/home#load_state', as: :load_state

  get '/about_us', to: 'spree/public#about_us', as: :about_us
  get '/privacy_policy', to: 'spree/public#privacy_policy', as: :privacy_policy
  get '/term_condition', to: 'spree/public#term_condition', as: :term_condition
  get '/coupon', to: 'spree/public#coupon', as: :coupon

  get '/404', to: 'spree/public#not_found'
  get '/422', to: 'spree/public#unacceptable'
  get '/500', to: 'spree/public#internal_error'
end

Spree::Core::Engine.routes.draw do
  get '/c/*id', to: 'taxons#show', as: :categories
  get '/m/*id', to: 'taxonomies#show', as: :menu
  get '/p/*id', to: 'products#show', as: :brandcruz_product
  get '/brands', to: 'brand#index', as: :brandcruz_brands
  get '/brands/*taxonomy', to: 'brand#index', as: :brandcruz_taxonomy_brands
  get '/b/*id', to: 'brand#show', as: :brandcruz_brand
  get '/product/search', to: 'products#keyword_search', as: :product_search
  get '/free-domestic-shipping-both-ways', to: 'public#domestic', as: :domestic
  match '/dedicated-customer-support', to: 'public#contact_us', via: [:get, :post], as: :contact_us
  get '/free-shipping-worldwide', to: 'public#international', as: :international
  get '/safe_shopping_guarantee', to: 'public#safe_shopping_guarantee', as: :safe_shopping_guarantee
  get '/secure_shopping', to: 'public#secure_shopping', as: :secure_shopping
  get '/forget_password', to: 'public#forget_password', as: :forget_password
  get '/welcome', to: 'public#welcome', as: :welcome
  get '/search_suggestion', to: 'home#search_suggestion', as: :search_suggestion
  get '/order/:id/shipped_track_now', to: 'orders#shipped_track', as: :shipped_track
  get '/admin/orders/:id/tracks', to: 'admin/orders#track', as: :admin_order_track
  get '/brand-cruz-frequently-asked-question', to: 'public#faq', as: :faq
  get '/checkout-sign-up', to: 'checkout#registration', as: :checkout_signup
  get '/secure-checkout-flow-cgn-shipping-address', to: 'checkout#edit', as: :checkout_address
  get '/secure-payment-flow-cng-capture', to: 'checkout#edit', as: :checkout_payment
  post '/apply_coupon', to: 'orders#apply_coupon', as: :apply_coupon
  get '/remove_coupon/:id', to: 'orders#remove_coupon', as: :remove_coupon
  get '/404', to: 'public#not_found'
  get '/422', to: 'public#unacceptable'
  get '/500', to: 'public#internal_error'
  get '/show_cc/:id', to: 'admin/payments#show_cc', as: :show_cc
  patch '/admin/order/:id/update_state/', to: 'admin/orders#update_state', as: :order_state

  devise_scope :spree_user do
    get '/secure-user-signin-signup', to: 'user_sessions#new', as: :user_session
  end
end

app/models/spree/address.rb
module Spree
  class Address < Spree::Base
    require 'twitter_cldr'

    belongs_to :country, class_name: "Spree::Country"
    belongs_to :state, class_name: "Spree::State"

    has_many :shipments, inverse_of: :address

    with_options presence: true do
      # validates :firstname, :lastname, :address1, :city, :country
      validates :address1, :city, :country
      validates :zipcode, if: :require_zipcode?
      validates :phone, if: :require_phone?
    end

    validate :state_validate, :postal_code_validate

    alias_attribute :first_name, :firstname
    alias_attribute :last_name, :lastname

    # self.whitelisted_ransackable_attributes = %w[firstname lastname company]

    def self.build_default
      new
    end

    def self.default(user = nil, kind = "bill")
      if user && user_address = user.public_send(:"#{kind}_address")
        user_address.clone
      else
        build_default
      end
    end

    # Can modify an address if it's not been used in an order (but checkouts controller has finer control)
    # def editable?
    #   new_record? || (shipments.empty? && checkouts.empty?)
    # end

    def name
      "#{first_name} #{last_name}".strip
    end

    def name=(full_name)
      f_name = full_name.split(' ', 2)
      self.first_name = f_name.first
      self.last_name = f_name.last if f_name.length > 1
    end

    def full_name
      "#{firstname} #{lastname}".strip
    end

    def state_text
      state.try(:abbr) || state.try(:name) || state_name
    end

    def same_as?(other)
      return false if other.nil?
      attributes.except('id', 'updated_at', 'created_at') == other.attributes.except('id', 'updated_at', 'created_at')
    end

    alias same_as same_as?

    def to_s
      "#{full_name}: #{address1}"
    end

    def clone
      self.class.new(self.attributes.except('id', 'updated_at', 'created_at'))
    end

    def ==(other_address)
      self_attrs = self.attributes
      other_attrs = other_address.respond_to?(:attributes) ? other_address.attributes : {}

      [self_attrs, other_attrs].each { |attrs| attrs.except!('id', 'created_at', 'updated_at') }

      self_attrs == other_attrs
    end

    def empty?
      attributes.except('id', 'created_at', 'updated_at', 'country_id').all? { |_, v| v.nil? }
    end

    # Generates an ActiveMerchant compatible address hash
    def active_merchant_hash
      {
          name: full_name,
          address1: address1,
          address2: address2,
          city: city,
          state: state_text,
          zip: zipcode,
          country: country.try(:iso),
          phone: phone
      }
    end

    def require_phone?
      true
    end

    def require_zipcode?
      true
    end

    private
    def state_validate
      # Skip state validation without country (also required)
      # or when disabled by preference
      return if country.blank? || !Spree::Config[:address_requires_state]
      return unless country.states_required

      # ensure associated state belongs to country
      if state.present?
        if state.country == country
          self.state_name = nil #not required as we have a valid state and country combo
        else
          if state_name.present?
            self.state = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure state_name belongs to country without states, or that it matches a predefined state name/abbr
      if state_name.present?
        if country.states.present?
          states = country.states.find_all_by_name_or_abbr(state_name)

          if states.size == 1
            self.state = states.first
            self.state_name = nil
          else
            errors.add(:state, :invalid)
          end
        end
      end

      # ensure at least one state field is populated
      errors.add :state, :blank if state.blank? && state_name.blank?
    end

    def postal_code_validate
      return if country.blank? || country.iso.blank? || !require_zipcode?
      return if !TwitterCldr::Shared::PostalCodes.territories.include?(country.iso.downcase.to_sym)

      postal_code = TwitterCldr::Shared::PostalCodes.for_territory(country.iso)
      errors.add(:zipcode, :invalid) if !postal_code.valid?(zipcode.to_s.strip)
    end
  end
end

app/models/spree/asset.rb
module Spree
  class Asset < Spree::Base
    belongs_to :viewable, polymorphic: true, touch: true
    acts_as_list scope: [:viewable_id, :viewable_type]
  end
end

app/models/spree/brand.rb
module Spree
  class Brand < ActiveRecord::Base
    extend FriendlyId
    friendly_id :slug_candidates, use: :slugged

    has_many :products, :class_name => 'Spree::Product'

    def slug_candidates
      [
          :name,
          [:name, :id],
      ]
    end

    def self.replace_macys
      mac_brands = self.where("lower(name) like '%macy%'")
      mac_brands.each do |br|
        if br.name.include? "Macy's"
          br.name = br.name.gsub("Macy's", "Brandcruz")
          br.slug = br.slug.present? ? br.slug.gsub("macy-s", "brandcruz") : 'brandcruz'
        else
          br.name = "Brandcruz"
          br.slug = "brandcruz"
        end
        br.save
        p "Info: ID: #{br.id} and url: #{br.slug}"
      end
    end

  end
end

app/models/spree/classification.rb
module Spree
  class Classification < Spree::Base
    self.table_name = 'spree_products_taxons'
    acts_as_list scope: :taxon

    with_options inverse_of: :classifications, touch: true do
      belongs_to :product, class_name: "Spree::Product"
      belongs_to :taxon, class_name: "Spree::Taxon"
    end

    validates :taxon, :product, presence: true
    # For #3494
    validates :taxon_id, uniqueness: { scope: :product_id, message: :already_linked, allow_blank: true }
  end
end

app/models/spree/credit_card.rb
module Spree
  class CreditCard < Spree::Base
    belongs_to :payment_method
    belongs_to :user, class_name: Spree.user_class, foreign_key: 'user_id'
    has_many :payments, as: :source

    before_save :set_last_digits

    after_save :ensure_one_default

    # As of rails 4.2 string columns always return strings, we can override it on model level.
    attribute :month, Type::Integer.new
    attribute :year, Type::Integer.new

    attr_reader :number
    attr_accessor :encrypted_data,
                  :imported,
                  :verification_value

    with_options if: :require_card_numbers?, on: :create do
      validates :month, :year, numericality: {only_integer: true}
      # validates :number, :verification_value, presence: true, unless: :imported
      validates :name, presence: true
    end

    scope :with_payment_profile, -> { where('gateway_customer_profile_id IS NOT NULL') }
    scope :default, -> { where(default: true) }

    # needed for some of the ActiveMerchant gateways (eg. SagePay)
    alias_attribute :brand, :cc_type

    # ActiveMerchant::Billing::CreditCard added this accessor used by some gateways.
    # More info: https://github.com/spree/spree/issues/6209
    #
    # Returns or sets the track data for the card
    #
    # @return [String]
    attr_accessor :track_data

    CARD_TYPES = {
        visa: /^4\d{12}(\d{3})?(\d{3})?$/,
        master: /^(5[1-5]\d{4}|677189|222[1-9]\d{2}|22[3-9]\d{3}|2[3-6]\d{4}|27[01]\d{3}|2720\d{2})\d{10}$/,
        discover: /^(6011|65\d{2}|64[4-9]\d)\d{12}|(62\d{14})$/,
        american_express: /^3[47]\d{13}$/,
        diners_club: /^3(0[0-5]|[68]\d)\d{11}$/,
        jcb: /^35(28|29|[3-8]\d)\d{12}$/,
        switch: /^6759\d{12}(\d{2,3})?$/,
        solo: /^6767\d{12}(\d{2,3})?$/,
        dankort: /^5019\d{12}$/,
        maestro: /^(5[06-8]|6\d)\d{10,17}$/,
        forbrugsforeningen: /^600722\d{10}$/,
        laser: /^(6304|6706|6709|6771(?!89))\d{8}(\d{4}|\d{6,7})?$/
    }

    def expiry=(expiry)
      return unless expiry.present?

      self[:month], self[:year] =
          if expiry.match(/\d{2}\s?\/\s?\d{2,4}/) # will match mm/yy and mm / yyyy
            expiry.delete(' ').split('/')
          elsif match = expiry.match(/(\d{2})(\d{2,4})/) # will match mmyy and mmyyyy
            [match[1], match[2]]
          end
      if self[:year]
        self[:year] = "20#{ self[:year] }" if self[:year] / 100 == 0
        self[:year] = self[:year].to_i
      end
      self[:month] = self[:month].to_i if self[:month]
    end

    def number=(num)
      @number = num.gsub(/[^0-9]/, '') rescue nil
    end

    # cc_type is set by jquery.payment, which helpfully provides different
    # types from Active Merchant. Converting them is necessary.
    def cc_type=(type)
      self[:cc_type] = case type
                         when 'mastercard', 'maestro' then
                           'master'
                         when 'amex' then
                           'american_express'
                         when 'dinersclub' then
                           'diners_club'
                         when '' then
                           try_type_from_number
                         else
                           type
                       end
    end

    def set_last_digits
      number.to_s.gsub!(/\s/, '')
      verification_value.to_s.gsub!(/\s/, '')
      self.last_digits ||= number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
    end

    def try_type_from_number
      numbers = number.delete(' ') if number
      CARD_TYPES.find { |type, pattern| return type.to_s if numbers =~ pattern }.to_s
    end

    def verification_value?
      verification_value.present?
    end

    # Show the card number, with all but last 4 numbers replace with "X". (XXXX-XXXX-XXXX-4338)
    def display_number
      "XXXX-XXXX-XXXX-#{last_digits}"
    end

    def actions
      %w{capture void credit}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      payment.pending? || payment.checkout?
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      !payment.failed? && !payment.void?
    end

    # Indicates whether its possible to credit the payment.  Note that most gateways require that the
    # payment be settled first which generally happens within 12-24 hours of the transaction.
    def can_credit?(payment)
      payment.completed? && payment.credit_allowed > 0
    end

    def has_payment_profile?
      gateway_customer_profile_id.present? || gateway_payment_profile_id.present?
    end

    # ActiveMerchant needs first_name/last_name because we pass it a Spree::CreditCard and it calls those methods on it.
    # Looking at the ActiveMerchant source code we should probably be calling #to_active_merchant before passing
    # the object to ActiveMerchant but this should do for now.
    def first_name
      name.to_s.split(/[[:space:]]/, 2)[0]
    end

    def last_name
      name.to_s.split(/[[:space:]]/, 2)[1]
    end

    def to_active_merchant
      ActiveMerchant::Billing::CreditCard.new(
          number: number,
          month: month,
          year: year,
          verification_value: verification_value,
          first_name: first_name,
          last_name: last_name,
      )
    end

    private

    def require_card_numbers?
      !self.encrypted_data.present? && !self.has_payment_profile?
    end

    def ensure_one_default
      if self.user_id && self.default
        CreditCard.where(default: true, user_id: self.user_id).where.not(id: self.id)
            .update_all(default: false)
      end
    end
  end
end

app/models/spree/member_product.rb
module Spree
  class MemberProduct < ActiveRecord::Base
    belongs_to :product, class_name: 'Spree::Product'
    belongs_to :member, class_name: 'Spree::Product', foreign_key: :member_id
  end
end

app/models/spree/order_track.rb
module Spree
  class OrderTrack < ActiveRecord::Base
    belongs_to :order, class_name: 'Spree::Order'
  end
end

app/models/spree/recommendation.rb
module Spree
  class Recommendation < ActiveRecord::Base
    belongs_to :product, class_name: 'Spree::Product'
    belongs_to :recommend_product, class_name: 'Spree::Product', foreign_key: :recommended_product_id

    def own_product
      Spree::Product.find_by_id(self.id)
    end
  end
end

app/models/spree/size.rb
module Spree
  class Size < ActiveRecord::Base
    belongs_to :product, :class_name => 'Spree::Product'
  end
end

app/models/spree/taxonomy.rb
module Spree
  class Taxonomy < Spree::Base
    acts_as_list
    extend FriendlyId
    friendly_id :name, use: :slugged

    validates :name, presence: true

    has_many :taxons, inverse_of: :taxonomy
    has_one :root, -> { where parent_id: nil }, class_name: "Spree::Taxon", dependent: :destroy

    has_many :top_categories, -> { where parent_id: nil }, class_name: "Spree::Taxon"

    after_create :set_root
    after_save :set_root_taxon_name

    default_scope { order("#{self.table_name}.position, #{self.table_name}.created_at") }

    private
    def set_root
      self.root ||= Taxon.create!(taxonomy_id: id, name: name)
    end

    def set_root_taxon_name
      root.update_attributes(name: name)
    end
  end
end

app/models/spree/user.rb
module Spree
  class User < Spree::Base
    include UserAddress
    include UserPaymentSource

    devise :database_authenticatable, :registerable, :recoverable,
           :rememberable, :trackable, :validatable, :encryptable, :encryptor => 'authlogic_sha512'
    devise :confirmable if Spree::Auth::Config[:confirmable]

    acts_as_paranoid
    after_destroy :scramble_email_and_password
    after_create :send_welcome_email

    has_many :orders

    before_validation :set_login

    users_table_name = User.table_name
    roles_table_name = Role.table_name

    scope :admin, -> { includes(:spree_roles).where("#{roles_table_name}.name" => "admin") }

    def self.admin_created?
      User.admin.count > 0
    end

    def admin?
      has_spree_role?('admin')
    end

    def send_welcome_email
      Spree::UserMailer.welcome(self).deliver_now
    end

    protected
    def password_required?
      !persisted? || password.present? || password_confirmation.present?
    end

    private

    def set_login
      # for now force login to be same as email, eventually we will make this configurable, etc.
      self.login ||= self.email if self.email
    end

    def scramble_email_and_password
      self.email = SecureRandom.uuid + "@example.net"
      self.login = self.email
      self.password = SecureRandom.hex(8)
      self.password_confirmation = self.password
      self.save
    end
  end
end

app/controllers/spree/admin/admin_base_decorator.rb
Spree::Admin::BaseController.class_eval do
  def authorize_admin
    if respond_to?(:model_class, true) && model_class
      record = model_class
    else
      record = Object
    end
    authorize! :admin, record
    authorize! action, record
  end
end

app/views/spree/products/_cart_form.html.erb
<%= form_for :order, url: populate_orders_path, remote: true, :html => {id: "order-populate"} do |f| %>
    <div class="row" id="inside-product-cart-form" data-hook="inside_product_cart_form">
      <%= hidden_field_tag "variant_id", @product.master.id %>
      <%= hidden_field_tag "size" %>
      <% if get_all_variant(@product.id).present? %>
          <div class="color-section">
            <span class="color-name"> Color: </span>

            <ul class="color-section-ul-style clearfix">
              <% get_all_variant(@product.id).each do |v| %>
                  <li>
                    <input type="radio" class="select_varient" id="radio_<%= v.id %>" data-color-name="<%= v.color %>" data-color-price="<%= get_varient_price(v.id) %>" name="variant_id" value="<%= v.id %>"/>
                    <label for="radio_<%= v.id %>"><span class="color_image" style="background: url(<%= v.color_image %>)"></span></label>
                  </li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <% if @product.product_sizes.present? %>
          <div class="flexible flex-items-xs-between" style="width: 100%">
            <div class="col-sm-12">
              <p class="medium">Size:</p>
            </div>
          </div>
      <% end %>
      <div class="size-wrapper" style="padding-left: 15px;">
        <div class="rowx space-10x size-container">
          <ul class="common-ul-style product-size clearfix">
            <% if @product.product_sizes.present? %>
                <% @product.product_sizes.each do |size| %>
                    <li class="">
                      <a class="size-selection" href="#" data-size_value="<%= size.short_name %>" href="#"><%= size.short_name %> </a>
                    </li>
                <% end %>
            <% end %>
          </ul>
        </div>
      </div>

      <% if @product.price_in(current_currency) && !@product.price.nil? %>
          <div data-hook="product_price" class="col-md-12">
            <% if @product.can_supply? %>
                <div class="add-to-cart">
                  <br/>

                  <div class="input-group">
                    <span>
					  <input id="counter" name="quantity" type="number" min="1" value="1" hidden>
                    </span>
                  </div>
                </div>
                <div class="alert alert-error hidden"></div>
                <span class="input-group-btn">
                  <% if @product.is_master? %>
                    <a href="#bottomArea" id="viewMemberItems_img" class="button button-primary button-full mb-20">
                      choose your items
                    </a>
                  <% else %>
                      <%= button_tag class: 'button button-primary button-full mb-20', style: "width:100%", id: 'add-to-cart-button', type: :submit do %>
                        ADD TO BAG
                      <% end %>
                  <% end %>
                </span>
            <% end %>
          </div>
      <% else %>
          <div id="product-price">
            <br/>

            <div>
              <span class="price selling">
                <%= Spree.t('product_not_available_in_this_currency') %>
              </span>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

<%= render 'spree/shared/service_unavailable_modal' %>

<script type="text/javascript">
    $(function () {
        var assets = {};
        <% @product.variants.each do |v| %>
        var vid = '<%= v.id %>';
        assets[vid] = {};
        <% v.images.each_with_index do |as, indx| %>
        assets[vid][<%= indx %>] = {
            image: '<%= as.image_link %>',
            zoom_image: '<%= as.zoomable_image_link.present? ? as.zoomable_image_link : as.image_link %>'
        };
        <%end%>
        <%end%>

        $(document).off('click', '.select_varient').on('click', '.select_varient', function () {
            id = $(this).val();
            var color_name = $(this).attr('data-color-name');
            var product_price = $(this).attr('data-color-price');
            $('.color-name').html("Color:    " + color_name);
            $('.product-price').html(product_price);
            $("#product-gallery").html('').removeClass("slick-initialized slick-slider slick-vertical");
            $('.zoomContainer').remove();
            $.each(assets[id], function (indx, img) {
                $("#product-gallery").append(tiny_item(img));
            });

            $("#product-zoom").elevateZoom({
                zoomType: "inner",
                responsive: !0,
                gallery: "product-gallery",
                cursor: "default",
                galleryActiveClass: "product-active"
            });

            setTimeout(function () {
                $("#product-gallery .selection:first-child").find('a').addClass('product-active').trigger('click');
            }, 100);

            attached_slider();

            if ($(".alert").text() == 'Please select color') {
                $(".alert").addClass('hidden');
            }
        });

        $('#order-populate').submit(function () {
            $('#service-unavailable').modal();
            return false;
            if ($('.select_varient').length >= 1 && !$('.select_varient').is(':checked')) {
                popupMessage('Please select color', 'alert-danger');
                return false
            }

            if ($('.size-selection').length >= 1 && $('#size').val() == '') {
                popupMessage('Please select size', 'alert-danger');
                return false
            }
        });
    });

    function tiny_item(images) {
        html = "<div class='selection'> <a href='#' data-image='" + images.image + "' data-zoom-image='" + images.zoom_image + "?op_sharpen=1&fit=fit,1&$filterlrg$&wid=1200&hei=1467', class=''>";
        html += "<img alt='' class='img-fluid' src='" + images.image + "'>";
        html += "</a> </div>";
        return html;
    }

    function attached_slider() {
        setTimeout(function () {
            $("#product-gallery").slick({
                infinite: false,
                slidesToShow: 4,
                slidesToScroll: 4,
                dots: false,
                vertical: true
            });
        }, 100);
    }
</script>

app/views/spree/products/_details.html.erb
<div class="product-detail">
  <div class="product-details-wrapper pdetail">
    <h2 class="p-title gothamHTFBook"><%= @product.brand.name if @product.brand.present? %></h2>

    <h1 class="p-cat-title gothamNarrowBold"><%= raw @product.name %></h1>

    <div class="p-prices clearfix">
      <div class="price-left pull-left">
        <h2 class="text-red current-price">Now <%= get_price_for_product(@product.id) %></h2>
      </div>
      <div class="price-right pull-left">
        <h3 class="original-price"><%= get_orginal_price_for_product(@product.id, 'Orig') %></h3>
      </div>
    </div>

    <%= render 'cart_form' %>
    <div class="product-accordion-wrapper">
      <div class="product-accordion-single">
        <div class="product-accordion-header accordion-header-active">
          <p>Details</p>

          <div class="header-icon"><i class="icon icon-cross"></i></div>
        </div>
        <div class="product-accordion-details">
          <p><%= raw remove_maycs(@product.description) %></p>
          <ul>
            <%= product_bullets(@product.bullets) %>
          </ul>
        </div>
      </div>
      <% if @product.sizechart.present? %>
          <div class="product-accordion-single">
            <div class="product-accordion-header">
              <p>Size Chart</p>

              <div class="header-icon"><i class="icon icon-cross"></i></div>
            </div>
            <div class="product-accordion-details table-responsive">
              <p><%= raw (@product.sizechart) %></p>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/products/_featured_category.html.erb
<% if @featured_category.present? %>
    <div class="col-sm-12" style="padding: 0 !important; margin: 0 !important; padding-top: 15px !important;">
      <p><strong> Featured Category</strong></p>
    </div>
    <div class="col-sm-12" style="padding: 0 !important; margin: 0 !important;">
      <% @featured_category.each do |cat| %>
          <div class="col-sm-6 col-md-4 col-lg-3 custom-column">
            <div class="product-item">

            </div>
            <!--<div id="chanelCatIconImgDiv" class="iconImgLarge">-->
            <a href="<%= category_url(cat) %>">
              <img src="<%= cat.featured_image %>" style="max-width: 100%;">
            </a>

            <div class="product-caption relative text-center gothamNarrowMedium">
              <a href="<%= category_url(cat) %>" style="margin: 0">
                <h2 id="cate_Furniture"><%= cat.name %></h2>
              </a>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/spree/products/_filter.html.erb
<aside class="aside">
  <ol class="breadcrumb transparent hidden-xs">
    <li><a href="#"><%= @taxon.top_taxon.name if @taxon.top_taxon.present? %> </a></li>
    <li class="active"><%= @taxon.name %></li>
  </ol>
  <%= render 'spree/products/filter_item' %>
</aside>

app/views/spree/products/_filter_item.html.erb
<div class="filters">
  <div class="filter-text gothamNarrowBold clearfix">
    Filter By
    <i class="glyphicon glyphicon-menu-down visible-xs pull-right"></i>
  </div>
  <div class="panel-group customPanel product-listing-panel category-sidebar-wrapper" id="accordion">

    <% @taxon.taxonomy.top_categories.each do |top_cat| %>
        <% if top_cat.sub_taxons.present? %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a role="button" data-toggle="collapse">
                    <%= top_cat.name %>
                  </a>
                </h4>
              </div>
              <div class="panel-collapse collapse in">
                <div class="panel-body">
                  <div class="filterboxes size-box">
                    <ul class="floated-list clearfix">
                      <% top_cat.sub_taxons.each do |sub| %>
                          <li style="width: 100%; float: none; text-align: left;">
                            <%= link_to sub.name, category_url(sub) %>
                          </li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/spree/products/_google_search_script.html.erb
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<%= raw @product.name %>",
  "image": "<%= get_image_for_product(@product, @product.master.images.first) %>",
  "description": "<%= raw remove_maycs(@product.description) %>",
  "mpn": "<%= @product.id %>",
  "brand": {
    "@type": "Thing",
    "name": "<%= @product.brand.name if @product.brand.present? %>"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "<%= rand(4.6..4.8).round(1) %>",
    "reviewCount": "<%= rand(126..559) %>"
  },
  "offers": {
    "@type": "Offer",
    "priceCurrency": "USD",
    "price": "<%= product_price_without_currency(@product.id) %>",
    "priceValidUntil": "2017-07-01",
    "itemCondition": "http://schema.org/Product",
    "availability": "http://schema.org/InStock",
    "seller": {
      "@type": "Organization",
      "name": "Brandcruz"
    }
  }
}

</script>

app/views/spree/products/_member_cart.html.erb
<%= hidden_field_tag "variant_id", product.master.id %>
<div class="alert alert-error hidden">
  <span class="notification-text"></span>
  <a class="close-notification">x</a>
</div>
<input id="counter" name="quantity" type="number" min="1" value="1" hidden>
<span class="input-group-btn">
    <%= button_tag class: 'button button-primary button-full mb-20 add-to-cart-button-cl add-to-cart-button', style: "width:100%", type: :submit do %>
       ADD TO BAG
    <% end %>
</span>