config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'

  get 'change_currency' => 'spree/home#change_currency'
  get 'save_change_currency' => 'spree/home#save_change_currency'
  get 'back_to_us' => 'spree/home#back_to_us'
  get 'get_currency_from_country' => 'spree/home#get_currency_from_country'

  resources :line_items, only: [:update, :destroy]
  resources :stores, only: [:edit_address]

  get 'load_state/:code', to: 'spree/home#load_state', as: :load_state

  get '/about_us', to: 'spree/public#about_us', as: :about_us
  get '/privacy_policy', to: 'spree/public#privacy_policy', as: :privacy_policy
  get '/term_condition', to: 'spree/public#term_condition', as: :term_condition
  get '/coupon', to: 'spree/public#coupon', as: :coupon

  get '/404', to: 'spree/public#not_found'
  get '/422', to: 'spree/public#unacceptable'
  get '/500', to: 'spree/public#internal_error'
end

Spree::Core::Engine.routes.draw do
  get '/c/*id', to: 'taxons#show', as: :categories
  get '/m/*id', to: 'taxonomies#show', as: :menu
  get '/p/*id', to: 'products#show', as: :brandcruz_product
  get '/brands', to: 'brand#index', as: :brandcruz_brands
  get '/brands/*taxonomy', to: 'brand#index', as: :brandcruz_taxonomy_brands
  get '/b/*id', to: 'brand#show', as: :brandcruz_brand
  get '/product/search', to: 'products#keyword_search', as: :product_search
  get '/free-domestic-shipping-both-ways', to: 'public#domestic', as: :domestic
  match '/dedicated-customer-support', to: 'public#contact_us', via: [:get, :post], as: :contact_us
  get '/free-shipping-worldwide', to: 'public#international', as: :international
  get '/safe_shopping_guarantee', to: 'public#safe_shopping_guarantee', as: :safe_shopping_guarantee
  get '/secure_shopping', to: 'public#secure_shopping', as: :secure_shopping
  get '/forget_password', to: 'public#forget_password', as: :forget_password
  get '/welcome', to: 'public#welcome', as: :welcome
  get '/search_suggestion', to: 'home#search_suggestion', as: :search_suggestion
  get '/order/:id/shipped_track_now', to: 'orders#shipped_track', as: :shipped_track
  get '/admin/orders/:id/tracks', to: 'admin/orders#track', as: :admin_order_track
  get '/brand-cruz-frequently-asked-question', to: 'public#faq', as: :faq
  get '/checkout-sign-up', to: 'checkout#registration', as: :checkout_signup
  get '/secure-checkout-flow-cgn-shipping-address', to: 'checkout#edit', as: :checkout_address
  get '/secure-payment-flow-cng-capture', to: 'checkout#edit', as: :checkout_payment
  post '/apply_coupon', to: 'orders#apply_coupon', as: :apply_coupon
  get '/remove_coupon/:id', to: 'orders#remove_coupon', as: :remove_coupon
  get '/404', to: 'public#not_found'
  get '/422', to: 'public#unacceptable'
  get '/500', to: 'public#internal_error'
  get '/show_cc/:id', to: 'admin/payments#show_cc', as: :show_cc
  patch '/admin/order/:id/update_state/', to: 'admin/orders#update_state', as: :order_state

  devise_scope :spree_user do
    get '/secure-user-signin-signup', to: 'user_sessions#new', as: :user_session
  end
end

app/controllers/spree/admin/orders/customer_details_controller.rb
module Spree
  module Admin
    module Orders
      class CustomerDetailsController < Spree::Admin::BaseController
        before_action :load_order
        before_action :load_user, only: :update, unless: :guest_checkout?

        def show
          edit
          render action: :edit
        end

        def edit
          country_id = Address.default.country.id
          @order.build_bill_address(country_id: country_id) if @order.bill_address.nil?
          @order.build_ship_address(country_id: country_id) if @order.ship_address.nil?

          @order.bill_address.country_id = country_id if @order.bill_address.country.nil?
          @order.ship_address.country_id = country_id if @order.ship_address.country.nil?
        end

        def update
          if @order.update_attributes(order_params)
            @order.associate_user!(@user, @order.email.blank?) unless guest_checkout?
            @order.next unless @order.complete?
            @order.refresh_shipment_rates(Spree::ShippingMethod::DISPLAY_ON_FRONT_AND_BACK_END)

            if @order.errors.empty?
              flash[:success] = Spree.t('customer_details_updated')
              redirect_to edit_admin_order_url(@order)
            else
              render action: :edit
            end
          else
            render action: :edit
          end
        end

        private

        def order_params
          params.require(:order).permit(
            :email,
            :use_shipping,
            bill_address_attributes: permitted_address_attributes,
            ship_address_attributes: permitted_address_attributes
          )
        end

        def load_order
          @order = Order.includes(:adjustments).friendly.find(params[:order_id])
        end

        def model_class
          Spree::Order
        end

        def load_user
          @user = (Spree.user_class.find_by(id: params[:user_id]) ||
            Spree.user_class.find_by(email: order_params[:email]))

          unless @user
            flash.now[:error] = Spree.t(:user_not_found)
            render :edit
          end
        end

        def guest_checkout?
          params[:guest_checkout] == 'true'
        end
      end
    end
  end
end

app/controllers/spree/admin/orders_controller.rb
module Spree
  module Admin
    class OrdersController < Spree::Admin::BaseController
      before_action :initialize_order_events
      before_action :load_order, only: [:edit, :update, :cancel, :resume, :approve, :resend, :open_adjustments, :close_adjustments, :cart, :update_state, :track]

      respond_to :html

      def index
        params[:q] ||= {}
        params[:q][:completed_at_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:q][:completed_at_not_null] == '1'
        params[:q][:s] ||= @show_only_completed ? 'completed_at desc' : 'created_at desc'
        params[:q][:completed_at_not_null] = '' unless @show_only_completed

        # As date params are deleted if @show_only_completed, store
        # the original date so we can restore them into the params
        # after the search
        created_at_gt = params[:q][:created_at_gt]
        created_at_lt = params[:q][:created_at_lt]

        params[:q].delete(:inventory_units_shipment_id_null) if params[:q][:inventory_units_shipment_id_null] == "0"

        if params[:q][:created_at_gt].present?
          params[:q][:created_at_gt] = Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day rescue ""
        end

        if params[:q][:created_at_lt].present?
          params[:q][:created_at_lt] = Time.zone.parse(params[:q][:created_at_lt]).end_of_day rescue ""
        end

        if @show_only_completed
          params[:q][:completed_at_gt] = params[:q].delete(:created_at_gt)
          params[:q][:completed_at_lt] = params[:q].delete(:created_at_lt)
        end

        @search = Order.preload(:user).accessible_by(current_ability, :index).ransack(params[:q])

        # lazy loading other models here (via includes) may result in an invalid query
        # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
        # see https://github.com/spree/spree/pull/3919
        @orders = @search.result(distinct: true).
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:orders_per_page])

        # Restore dates
        params[:q][:created_at_gt] = created_at_gt
        params[:q][:created_at_lt] = created_at_lt
      end

      def new
        @order = Order.create(order_params)
        redirect_to cart_admin_order_url(@order)
      end

      def edit
        can_not_transition_without_customer_info

        unless @order.completed?
          @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_FRONT_AND_BACK_END)
        end
      end

      def cart
        unless @order.completed?
          @order.refresh_shipment_rates
        end
        if @order.shipments.shipped.count > 0
          redirect_to edit_admin_order_url(@order)
        end
      end

      def update
        if @order.update_attributes(params[:order]) && @order.line_items.present?
          @order.update_with_updater!
          unless @order.completed?
            # Jump to next step if order is not completed.
            redirect_to admin_order_customer_path(@order) and return
          end
        else
          @order.errors.add(:line_items, Spree.t('errors.messages.blank')) if @order.line_items.empty?
        end

        render action: :edit
      end

      def update_state
        order_params = params[:order]
        status = order_params[:shipment_state]
        update_params = {}
        if 'payment_failed' == status
          update_params = {
              state: 'payment',
              payment_state: 'failed',
              shipment_state: nil,
              approved_at: '',
              shipped_at: nil,
              confirmation_delivered: nil
          }
        else
          update_params = {
              shipment_state: status == 'processing' ? nil : status,
              shipment_date: format_date(order_params[:shipment_date]),
              shipment_progress: order_params[:shipment_progress].present? ? order_params[:shipment_progress] : 0,
              shipped_at: (!@order.shipped_at.present? && status == 'shipped') ? DateTime.now : @order.shipped_at,
              payment_state: status == 'shipped' ? 'paid' : @order.payment_state
          }
        end
        if @order.update_attributes(update_params)
          comments = params[:comments].present? ? params[:comments] : "Order status updated to #{Spree::Order::ORDER_SHIPMENT_STATE[status.to_sym]}"
          @order.order_tracks.create(comment: comments, user_id: spree_current_user.id)
          flash[:success] = 'Order status has been updated'
          if @order.shipment_state == 'shipped'
            Spree::OrderMailer.update_order(@order).deliver_now
          end
          redirect_to :back
        else
          render :edit
        end
      end

      def track
        @trackes = @order.order_tracks.order('created_at').group_by { |track| track.created_at.strftime('%A, %d %b') }
      end

      def cancel
        @order.canceled_by(try_spree_current_user)
        flash[:success] = Spree.t(:order_canceled)
        redirect_to :back
      end

      def resume
        @order.resume!
        flash[:success] = Spree.t(:order_resumed)
        redirect_to :back
      end

      def approve
        @order.approved_by(try_spree_current_user)
        flash[:success] = Spree.t(:order_approved)
        unless @order.shipments.present?
          #number = SecureRandom.hex
          #shipment = @order.shipments.create!(number: number, address_id: @order.ship_address.id, cost: 0, state: 'pending')
          #free_shipping = Spree::ShippingMethod.find_by_code('0')
          #Spree::ShippingRate.create!(shipment_id: shipment.id, shipping_method_id: free_shipping.id)
        end
        redirect_to :back
      end

      def resend
        OrderMailer.confirm_email(@order.id, true).deliver_later
        flash[:success] = Spree.t(:order_email_resent)

        redirect_to :back
      end

      def open_adjustments
        adjustments = @order.all_adjustments.closed
        adjustments.update_all(state: 'open')
        flash[:success] = Spree.t(:all_adjustments_opened)

        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      def close_adjustments
        adjustments = @order.all_adjustments.open
        adjustments.update_all(state: 'closed')
        flash[:success] = Spree.t(:all_adjustments_closed)

        respond_with(@order) { |format| format.html { redirect_to :back } }
      end

      private
      def order_params
        params[:created_by_id] = try_spree_current_user.try(:id)
        params.permit(:created_by_id, :user_id)
      end

      def format_date(date)
        if date.present?
          dates = date.split('/')
          "#{dates.last}-#{dates.first}-#{dates.second}"
        else
          nil
        end
      end

      def load_order
        @order = Order.includes(:adjustments).friendly.find(params[:id])
        authorize! action, @order
      end

      # Used for extensions which need to provide their own custom event links on the order details view.
      def initialize_order_events
        @order_events = %w{approve cancel resume}
      end

      def model_class
        Spree::Order
      end
    end
  end
end

app/views/spree/admin/orders/_add_product.html.erb
<%= render partial: "spree/admin/variants/autocomplete", formats: :js %>
<%= render partial: "spree/admin/variants/autocomplete_stock", formats: :js %>

<div class="panel panel-default" id="add-line-item" data-hook>
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= Spree.t(:add_product) %>
    </h1>
  </div>
  <div class="panel-body">
    <div data-hook="add_product_name">
      <%= label_tag :add_variant_id, Spree.t(:name_or_sku) %>
      <%= hidden_field_tag :add_variant_id, "", class: "variant_autocomplete fullwidth-input" %>
    </div>

    <div id="stock_details"></div>
  </div>
</div>

app/views/spree/admin/orders/_adjustments.html.erb
<% if adjustments.eligible.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= title %>
      </h1>
    </div>
    
    <table class="table table-bordered">
      <thead>
        <th><%= Spree.t('name')%></th>
        <th><%= Spree.t('amount')%></th>
      </thead>
      <tbody id="order-charges" data-hook="order_details_adjustments">
        <% adjustments.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td>
              <strong><%= label %>:</strong>
            </td>
            <td class="total">
              <span>
                <%= Spree::Money.new(
                  adjustments.sum(&:amount), 
                  currency: adjustments.first.order.try(:currency)
                ) %>
              </span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/_form.html.erb
 <div data-hook="admin_order_form_fields">
  <% if @line_item.try(:errors).present? %>
    <%= render 'spree/admin/shared/error_messages', target: @line_item %>
  <% end %>

  <% if Spree::Order.checkout_step_names.include?(:delivery) %>
    <%= render partial: "spree/admin/orders/shipment", collection: @order.shipments.order(:created_at), locals: {order: order} %>
  <% else %>
    <%= render "spree/admin/orders/line_items", order: order %>
  <% end %>

  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.line_item_adjustments,
        order: order,
        title: Spree.t(:line_item_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.shipment_adjustments,
        order: order,
        title: Spree.t(:shipment_adjustments)
  %>
  <%= render "spree/admin/orders/adjustments",
        adjustments: @order.adjustments,
        order: order,
        title: Spree.t(:order_adjustments)
  %>

  <%= javascript_tag do %>
    var order_number = '<%= @order.number %>';
    var shipments = [];

    <% @order.shipments.each do |shipment| %>
      shipments.push(
        <%== shipment.as_json(
          root: false,
          only: [
            :id, :tracking, :number, :state, :stock_location_id
          ], include: [
            :inventory_units, :stock_location
          ]).to_json
        %>
      );
    <% end %>

    <%= render partial: 'spree/admin/shared/update_order_state', handlers: [:js] %>
  <% end %>
</div>

app/views/spree/admin/orders/_line_item.html.erb
<tr id="<%= spree_dom_id(f.object) %>" data-hook="admin_order_form_line_item_row">
  <td>
    <%=f.object.variant.product.name%> 
    <%= "(#{f.object.variant.options_text})" unless f.object.variant.option_values.empty? %>
  </td>
  <td class="price ">
    <%= f.object.single_money %>
  </td>
  <td class="qty">
    <%= f.number_field :quantity, min: 0, class: "qty" %>
  </td>
  <td class="total">
    <%= f.object.display_amount %>
  </td>
  <td data-hook="admin_order_form_line_item_actions" class="actions">
    <%= link_to_delete f.object, { 
      url: spree.admin_order_line_item_url(@order.number, f.object), 
      no_text: true 
    } %>
  </td>
</tr>

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:order_line_items) %>
      </h1>
    </div>
    <table class="table table-bordered line-items" data-hook="line-items">
      <thead>
        <th colspan="2"><%= Spree.t(:name) %></th>
        <th class="text-center"><%= Spree.t(:price) %></th>
        <th class="text-center"><%= Spree.t(:quantity) %></th>
        <th class="text-center"><%= Spree.t(:total_price) %></th>
        <th class="orders-actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
      </thead>
      <tbody>
        <% order.line_items.each do |item| %>
          <tr class="line-item" id="line-item-<%= item.id %>">
            <td class="line-item-image image text-center">
              <%= mini_image(item.variant) %>
            </td>
            <td class="line-item-name text-center">
              <%= item.variant.product.name %><br><%= "(" + variant_options(item.variant) + ")" unless item.variant.option_values.empty? %>
            </td>
            <td class="line-item-price text-center"><%= item.single_money.to_html %></td>
            <td class="line-item-qty-show text-center">
              <%= item.quantity %>
            </td>
            <td class="line-item-qty-edit is-hidden">
              <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
            </td>
            <td class="line-item-total text-center"><%= line_item_shipment_price(item, item.quantity) %></td>
            <td class="cart-line-item-delete actions actions-4 text-center" data-hook="cart_line_item_delete">
              <% if can? :update, item %>
                <%= link_to_with_icon 'arrow-left', Spree.t('actions.cancel'), "#", class: 'cancel-line-item btn btn-default btn-sm', data: {action: 'cancel'}, title: Spree.t('actions.cancel'), style: 'display: none', no_text: true %>
                <%= link_to_with_icon 'save', Spree.t('actions.save'), "#", class: 'save-line-item btn btn-success btn-sm', no_text: true, data: { :'line-item-id' => item.id, action: 'save'}, title: Spree.t('actions.save'), style: 'display: none' %>
                <%= link_to_with_icon 'edit', Spree.t('edit'), "#", class: 'edit-line-item btn btn-primary btn-sm', data: {action: 'edit'}, title: Spree.t('edit'), no_text: true %>
                <%= link_to_with_icon 'delete', Spree.t('delete'), "#", class: 'delete-line-item btn btn-danger btn-sm', data: { 'line-item-id' => item.id, action: 'remove'}, title: Spree.t('delete'), no_text: true %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
    <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_order), new_admin_order_url, :class => "btn-success", :icon => 'add', :id => 'admin_new_order' %>
<% end if can? :create, Spree::Order %>

<% content_for :table_filter do %>
    <div data-hook="admin_orders_index_search">

      <%= search_form_for [:admin, @search] do |f| %>
          <div class="row">
            <div class="date-range-filter col-md-8">
              <div class="form-group">
                <%= label_tag :q_created_at_gt, Spree.t(:date_range) %>
                <div class="row no-padding-bottom">
                  <div class="col-md-6">
                    <div class="input-group">
                      <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>
                      <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                    </div>

                  </div>
                  <div class="col-md-6">
                    <div class="input-group">
                      <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
                      <span class="input-group-addon">
                    <i class="icon icon-calendar"></i>
                  </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_number_cont, Spree.t(:order_number, :number => '') %>
                <%= f.text_field :number_cont, class: 'form-control js-quick-search-target' %>
              </div>
            </div>

          </div>

          <div class="row">

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_state_eq, Spree.t(:status) %>
                <%= f.select :state_eq, Spree::Order.state_machines[:state].states.map { |s| [Spree.t("order_state.#{s.name}"), s.value] }, {:include_blank => true}, :class => 'select2 js-filterable' %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_payment_state_eq, Spree.t(:payment_state) %>
                <%= f.select :payment_state_eq, Spree::Order::PAYMENT_STATES.map { |s| [Spree.t("payment_states.#{s}"), s] }, {:include_blank => true}, :class => 'select2 js-filterable' %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_shipment_state_eq, Spree.t(:shipment_state) %>
                <%= f.select :shipment_state_eq, Spree::Order::SHIPMENT_STATES.map { |s| [Spree.t("shipment_states.#{s}"), s] }, {:include_blank => true}, :class => 'select2 js-filterable' %>
              </div>
            </div>

          </div>

          <div class="row">

            <!--<div class="col-md-4">-->
            <!--<div class="form-group">-->
            <!--<%#= label_tag :q_bill_address_firstname_start, Spree.t(:first_name_begins_with) %>-->
            <!--<%#= f.text_field :bill_address_firstname_start, class: 'form-control' %>-->
            <!--</div>-->
            <!--</div>-->

            <!--<div class="col-md-4">-->
            <!--<div class="form-group">-->
            <!--<%#= label_tag :q_bill_address_lastname_start, Spree.t(:last_name_begins_with) %>-->
            <!--<%#= f.text_field :bill_address_lastname_start, class: 'form-control' %>-->
            <!--</div>-->
            <!--</div>-->

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_email_cont, Spree.t(:email) %>
                <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
              </div>
            </div>

          </div>

          <div class="row">

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_line_items_variant_sku_eq, Spree.t(:sku) %>
                <%= f.text_field :line_items_variant_sku_eq, class: 'form-control' %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :q_promotions_id_in, Spree.t(:promotion) %>
                <%= f.select :promotions_id_in, Spree::Promotion.applied.pluck(:name, :id), {:include_blank => true}, :class => 'select2' %>
              </div>
            </div>

            <div class="col-md-4">

              <div class="form-group">

                <div class="checkbox">
                  <%= label_tag 'q_completed_at_not_null' do %>
                      <%= f.check_box :completed_at_not_null, {:checked => @show_only_completed}, '1', '0' %>
                      <%= Spree.t(:show_only_complete_orders) %>
                  <% end %>
                </div>

                <div class="checkbox">
                  <%= label_tag 'q_considered_risky_eq' do %>
                      <%= f.check_box :considered_risky_eq, {:checked => (params[:q][:considered_risky_eq] == '1')}, '1', '' %>
                      <%= Spree.t(:show_only_considered_risky) %>
                  <% end %>
                </div>

              </div>

            </div>

          </div>

          <div data-hook="admin_orders_index_search_buttons" class="form-actions">
            <%= button Spree.t(:filter_results), 'search' %>
          </div>

      <% end %>

    </div>

<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders %>

<% if @orders.any? %>
    <table class="table" id="listing_orders" data-hook>
      <thead>
      <tr data-hook="admin_orders_index_headers">
        <% if @show_only_completed %>
            <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% else %>
            <th><%= sort_link @search, :created_at, I18n.t(:created_at, :scope => 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :number, I18n.t(:number, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :considered_risky, I18n.t(:considered_risky, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :state, I18n.t(:state, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :payment_state, I18n.t(:payment_state, :scope => 'activerecord.attributes.spree/order') %></th>
        <% if Spree::Order.checkout_step_names.include?(:delivery) %>
            <th><%= sort_link @search, :shipment_state, I18n.t(:shipment_state, :scope => 'activerecord.attributes.spree/order') %></th>
        <% end %>
        <th><%= sort_link @search, :email, I18n.t(:email, :scope => 'activerecord.attributes.spree/order') %></th>
        <th><%= sort_link @search, :total, I18n.t(:total, :scope => 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
          <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
            <td>
              <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
            </td>
            <td><%= link_to order.number, edit_admin_order_path(order) %></td>
            <td>
          <span class="label label-<%= order.considered_risky ? 'considered_risky' : 'considered_safe' %>">
            <%= order.considered_risky ? Spree.t("risky") : Spree.t("safe") %>
          </span>
            </td>
            <td>
              <span class="label label-<%= order.state.downcase %>"><%= Spree.t("order_state.#{order.state.downcase}") %></span>
              <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
            </td>
            <td>
              <% if order.payment_state %>
                  <span class="label label-<%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) %></span>
                  <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_payment_state_eq" data-ransack-value="<%= order.payment_state %>"></span>
              <% end %>
            </td>
            <% if Spree::Order.checkout_step_names.include?(:delivery) %>
                <td>
                  <% if order.shipment_state %>
                      <span class="label label-<%= order.shipment_state %>"><%= Spree.t("shipment_states.#{order.shipment_state}") %></span>
                      <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
                  <% end %>
                </td>
            <% end %>
            <td>
              <% if order.user %>
                  <%= link_to order.email, edit_admin_user_path(order.user) %>
              <% else %>
                  <%= mail_to order.email %>
              <% end %>
              <% if order.user || order.email %>
                  <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_email_cont" data-ransack-value="<%= order.email %>"></span>
              <% end %>
            </td>
            <td><%= order.display_total.to_html %></td>
            <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
              <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
      <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
    </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>